import os
import smtplib
import pandas as pd
import numpy as np
from flask import Flask, render_template, request, flash
from werkzeug.utils import secure_filename
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders

app = Flask(__name__)
app.secret_key = "supersecretkey"
UPLOAD_FOLDER = 'uploads'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

# --- CONFIGURATION ---
SENDER_EMAIL = "atharvapandey100@gmail.com"     # <--- PUT YOUR EMAIL HERE
SENDER_PASSWORD = "azlp blsr czrx lhrp"     # <--- PUT YOUR APP PASSWORD HERE

os.makedirs(UPLOAD_FOLDER, exist_ok=True)

def calculate_topsis(file_path, weights, impacts):
    data = None
    try:
        filename, file_extension = os.path.splitext(file_path)
        file_extension = file_extension.lower()

        if file_extension == '.xlsx':
            data = pd.read_excel(file_path)
        elif file_extension == '.csv':
            data = pd.read_csv(file_path, encoding='latin1')
        else:
            return None, "Error: Unsupported file format. Please upload .xlsx or .csv."

    except FileNotFoundError:
        return None, "Error: Input file not found."
    except Exception as e:
        return None, f"Error reading file: {str(e)}"

    if data.shape[1] < 3:
        return None, "Error: Input file must contain at least three columns."

    original_df = data.copy()
    criteria_data = data.iloc[:, 1:].copy()

    try:
        df_numeric = criteria_data.astype(float)
    except ValueError:
        return None, "Error: All criteria values (columns 2 onwards) must be numeric."

    if len(df_numeric.columns) != len(weights):
        return None, f"Error: Input has {len(df_numeric.columns)} numeric columns, but you provided {len(weights)} weights."

    try:
        normalized_df = df_numeric.div(np.sqrt((df_numeric**2).sum()), axis=1)
        weighted_df = normalized_df.mul(weights, axis=1)

        ideal_best = []
        ideal_worst = []

        for i, col in enumerate(weighted_df.columns):
            if impacts[i] == '+':
                ideal_best.append(weighted_df[col].max())
                ideal_worst.append(weighted_df[col].min())
            else:
                ideal_best.append(weighted_df[col].min())
                ideal_worst.append(weighted_df[col].max())

        dist_best = np.sqrt(((weighted_df - ideal_best) ** 2).sum(axis=1))
        dist_worst = np.sqrt(((weighted_df - ideal_worst) ** 2).sum(axis=1))
        score = dist_worst / (dist_best + dist_worst)
        
        original_df['Topsis Score'] = score
        # FORCE RANK TO INTEGER
        original_df['Rank'] = score.rank(ascending=False).astype(int)
        
        return original_df, None

    except Exception as e:
        return None, f"Calculation Error: {str(e)}"

def send_email(receiver_email, result_file_path, df_result):
    msg = MIMEMultipart('alternative')
    msg['From'] = SENDER_EMAIL
    msg['To'] = receiver_email
    msg['Subject'] = "Topsis Results (Table & File)"

    # --- CREATE HTML TABLE WITH FULL BORDERS ---
    # We use 'border=1' for email client compatibility and strict CSS for styling
    html_table = df_result.to_html(index=False, border=1)
    
    html_content = f"""
    <html>
      <head>
      <style>
        /* Force borders on everything */
        table {{
            border-collapse: collapse;
            width: 100%;
            font-family: Arial, sans-serif;
            font-size: 14px;
            border: 2px solid #333; /* Thick outer border */
        }}
        th, td {{
            border: 1px solid #000000 !important; /* Force black borders on cells */
            padding: 10px;
            text-align: center;
        }}
        th {{
            background-color: #009879; /* Header Color */
            color: white;
            font-weight: bold;
        }}
        tr:nth-child(even) {{
            background-color: #f2f2f2; /* Zebra striping */
        }}
        tr:hover {{
            background-color: #ddd;
        }}
      </style>
      </head>
      <body style="font-family: Arial, sans-serif; color: #333;">
        <h2 style="color: #2e7d32;">Here are your TOPSIS Results</h2>
        <p>Please find the result file attached. Below is the summary table:</p>
        <br>
        
        {html_table}
        
        <br>
        <p style="font-size:12px; color: #777;">Generated by Topsis Webservice</p>
      </body>
    </html>
    """
    
    msg.attach(MIMEText(html_content, 'html'))

    # Attach CSV File
    filename = os.path.basename(result_file_path)
    with open(result_file_path, "rb") as attachment:
        part = MIMEBase('application', 'octet-stream')
        part.set_payload(attachment.read())
        encoders.encode_base64(part)
        part.add_header('Content-Disposition', f"attachment; filename= {filename}")
        msg.attach(part)

    # Send
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(SENDER_EMAIL, SENDER_PASSWORD)
    server.sendmail(SENDER_EMAIL, receiver_email, msg.as_string())
    server.quit()

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        if 'file' not in request.files:
            flash("No file part")
            return render_template('index.html')
            
        file = request.files['file']
        weights_str = request.form['weights']
        impacts_str = request.form['impacts']
        email_id = request.form['email']

        if file.filename == '':
            flash("No selected file")
            return render_template('index.html')

        try:
            weights = [float(w) for w in weights_str.split(',')]
            impacts = [i.strip() for i in impacts_str.split(',')]
        except ValueError:
            flash("Invalid format for weights/impacts.")
            return render_template('index.html')

        if len(weights) != len(impacts):
            flash("Counts mismatch: Weights vs Impacts.")
            return render_template('index.html')
        
        filename = secure_filename(file.filename)
        filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
        file.save(filepath)

        result_df, error = calculate_topsis(filepath, weights, impacts)
        
        if error:
            flash(error)
            return render_template('index.html')

        result_filename = f"result_{os.path.splitext(filename)[0]}.csv"
        result_path = os.path.join(app.config['UPLOAD_FOLDER'], result_filename)
        result_df.to_csv(result_path, index=False)

        try:
            send_email(email_id, result_path, result_df)
            flash(f"Success! Check {email_id} for results.")
        except Exception as e:
            flash(f"Error sending email: {e}")

    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)